<section class="about">
    <div class="about__header">
        <img alt="main-banner" src="./assets/images/main-banner1.png" />
        <h1>ABOUT</h1>
    </div>

    <div class="about__details">
        <div class="about__details-block">
            <img alt="about" src="./assets/images/about-1.png" />
            <span>FirstLine Recovery is the <b>leading provider of vehicle recovery, maintenance and repair services, roadside assistance and secure vehicle storage</b> in London, Surrey, Sussex, Essex and Kent. If you need regular servicing and maintenance on either one or an entire fleet of vehicles, Firstline can provide you with a fully comprehensive service at the <b>most competitive rates available</b>.</span>
        </div>
        <div class="about__details-block">
            <img alt="about" src="./assets/images/about-2.png" />
            <span>
                Our goal is to provide <b>high quality, customer friendly services</b> to all of our clients. So whether your car has broken down and you need roadside assistance, you've lost your keys and require a quick vehicle recovery or you are just looking for a reliable company to carry out regular servicing and maintenance, FirstLine can provide quick and efficient <b>assistance in as little as 60 minutes from your call</b>.</span>
        </div>
    </div>

    <div class="about__events" data-flickity='{ "freeScroll": true, "cellSelector":".about__events-content__item","wrapAround":true,"watchCSS":true,"pageDots":false,"prevNextButtons":false,"pauseAutoPlayOnHover":false,"accessibility":false  }'>
        <h1>EVENTS YOU'LL FIND US AT</h1>
        <ul class="about__events-content">
            <li class="about__events-content__item">
                <a href="">
                    <div><img src="./assets/images/event-1.png" /></div>
                </a>
            </li>
            <li class="about__events-content__item">
                <a href="">
                    <div><img src="./assets/images/event-2.png" /></div>
                </a>
            </li>
            <li class="about__events-content__item">
                <a href="">
                    <div><img src="./assets/images/event-3.png" /></div>
                </a>
            </li>
        </ul>
    </div>

    <div class="about__fleet">
        <h1>See Our Fleet..</h1>
        <div class="about__fleet-carousel" data-flickity='{"pageDots": false, "wrapAround": true, "autoPlay": 2000}'>
            <div class="about__fleet-carousel__item"><img alt="fleet vehicles" src="./assets/images/fleet-1.jpg" /></div>
            <div class="about__fleet-carousel__item"><img alt="fleet vehicles" src="./assets/images/fleet-2.jpg" /></div>
            <div class="about__fleet-carousel__item"><img alt="fleet vehicles" src="./assets/images/fleet-3.jpg" /></div>
            <div class="about__fleet-carousel__item"><img alt="fleet vehicles" src="./assets/images/fleet-4.jpg" /></div>
            <div class="about__fleet-carousel__item"><img alt="fleet vehicles" src="./assets/images/fleet-5.jpg" /></div>
            <div class="about__fleet-carousel__item"><img alt="fleet vehicles" src="./assets/images/fleet-6.jpg" /></div>
            <div class="about__fleet-carousel__item"><img alt="fleet vehicles" src="./assets/images/fleet-7.jpg" /></div>
            <div class="about__fleet-carousel__item"><img alt="fleet vehicles" src="./assets/images/fleet-8.jpg" /></div>
        </div>
    </div>
</section>