<section class="cookie-policy">
    <div class="cookie-policy__header">
        <h1>FirstLine Recovery Cookie Policy</h1>
    </div>

    <div class="cookie-policy__content">
        <b>Last updated:</b> August 2023
        <p>
            At FirstLine Recovery ("we", "our", or "us"), we utilise cookies on our website firstline-recovery.co.uk (the "Site") to enhance your browsing experience. By accessing and using our Site, you agree to our use of cookies.
        </p>
        <p>
            This Cookie Policy provides detailed information about what cookies are, our application of cookies, potential third-party involvement, your available choices regarding cookies, and additional cookie-related facts.
        </p>
        <p>
            <b>Understanding Cookies</b>
            <br />
            Cookies are tiny data fragments exchanged between your web browser and a website you visit. These data bits are stored in your browser, allowing the Site or a third-party to recognise you, thereby facilitating your subsequent visits and enhancing the Site's utility.
        </p>
        <p>
            Cookies can be categorised into "persistent" or "session" cookies.
        </p>
        <p>
            <b>FirstLine Recovery's Application of Cookies</b>
            <br />
            When you access and use our Site, we may introduce several cookie files into your web browser.
        </p>
        <p>
            Our use of cookies serves various purposes: they enable certain Site functions, assist with analytics, remember your preferences, and support the delivery of targeted advertising.
        </p>
        <p>
            We employ both session and persistent cookies on the Site, incorporating various cookie types to optimise the site, please see below.
        </p>
        <p>
            <b>Essential Cookies</b>: These are vital for user authentication and prevention of fraudulent user activities.
        </p>
        <p>
            <b>Third-party Cookies</b>
            Beyond our own cookies, we may utilise third-party cookies to gather usage statistics of the Site, deliver advertisements on and through the Site, among other functionalities.
        </p>
        <p>
            <b>Your Cookie Choices</b>
            You can manage how cookies interact with your device by adjusting your browser's settings. If you choose to delete or refuse cookies, please note that this may impact your ability to use all the features we offer, store your preferences, or properly display our pages.
        </p>
        For more information on how to manage or delete cookies, we recommend referring to your browser's official support or documentation, or online resources providing comprehensive information on cookie management.

    </div>
</section>