<section class="services">
    <div class="services__header">
        <img src="./assets/images/main-banner2.png" />
        <h1>SERVICES</h1>
        <span>
            We provide a wide range of vehicle recovery, maintenance, repair and collection services. Please browse our individual service for more information, or get in touch - <b>&nbsp;0203 976 1066</b>
        </span>
    </div>

    <div class="services__buttons">
        <ul>
            <li><a href="#breakdown-recovery">Breakdown Recovery</a></li>
            <li><a href="#roadside-assistance">Roadside Assistance</a></li>
            <li><a href="#accident-recovery">Accident Recovery</a></li>
            <li><a href="#vehicle-storage">Vehicle Storage</a></li>
            <li><a href="#vehicle-transportation">Vehicle Transportation</a></li>
            <li><a href="#police-collections">Police & Compound Collections</a></li>
        </ul>
        <ul>
            <li><a href="#abandoned-removal">Abandoned Vehicle Removal</a></li>
            <li><a href="#bailiff-recovery">Bailiff Recovery</a></li>
            <li><a href="#keyless-recovery">Keyless/Total Key Lift Recovery</a></li>
            <li><a href="#commercial-recovery">Commercial Recovery</a></li>
            <li><a href="#fleet-services">Fleet Vehicle Services</a></li>
            <li><a href="#scrap-vehicle">Scrap Vehicle Collections</a></li>
        </ul>
    </div>


    <div class="services__search">
        <input class="services__search-input" id="search" type="text" placeholder="Search for Keyword/Service" />
    </div>

    <div class="services__list">

        <div class="services__list-content">
            <hr id="breakdown-recovery" />
            <h1>Breakdown Recovery</h1>
            <div class="services__list-content__item">
                <span>
                    Experiencing a breakdown can be daunting, especially on long journeys. At FirstLine Recovery, we provide fast, reliable assistance. Using GPS tracking, we locate you quickly, send the closest recovery vehicle, and keep you updated on our arrival.
                    <br />
                    <br />
                    We cater to all sorts of vehicles, ensuring comfort with amenities like blankets, water, and phone charging. If a quick fix isn't possible, we'll transport your vehicle and passengers safely to your desired location. Our 24/7 service covers London, Surrey, Sussex, Essex, and Kent, ready to assist whenever you need us.
                </span>
                <img src="./assets/images/breakdown-service.png" />
            </div>
        </div>


        <div class="services__list-content">
            <hr id="roadside-assistance" />
            <h1>Roadside Assistance</h1>
            <div class="services__list-content__item">

                <span>
                    FirstLine Recovery is available 24/7 to assist motorists in cars, vans, motorbikes, motorhomes, and commercial vehicles across London, Surrey, Sussex, Essex, and Kent. We understand that unexpected breakdowns, like flat tyres, battery issues, lost keys, or even fuel mishaps, can disrupt your journey. That's why our roadside assistance team, equipped with GPS tracking technology, is ready for rapid response.
                    <br />
                    <br />
                    Our skilled drivers will provide tyre changes, fuel decontamination, jump starts, and emergency vehicle access, all while ensuring your comfort with amenities like water and blankets. In the event of fuel contamination, remember to remove the ignition keys and avoid starting the car to prevent further damage. We'll move your vehicle to a facility for fuel replacement, disposing all waste responsibly.
                    <br />
                    <br />
                    For emergency vehicle access, a simple roadside disclaimer will be completed before we initiate our lockout service. Reach out to us anytime and we'll get you back on the road promptly.
                </span>
                <img alt="roadside assistance" src="./assets/images/roadside-assistance.png" />
            </div>
        </div>

        <div class="services__list-content">

            <hr id="accident-recovery" />
            <h1>Accident Recovery</h1>
            <div class="services__list-content__item">
                <span>
                    FirstLine Recovery provides professional all-terrain accident recovery services in London, Surrey, Sussex, Essex, and Kent. If you find yourself in an accident, once it's safe to do so, reach out to us for efficient vehicle recovery or repair. Our office staff, adept in handling distressed callers, will swiftly gather necessary information and dispatch our closest recovery specialist, thanks to GPS tracking in all our vehicles.
                    <br />
                    <br />
                    Upon arrival, our expert will assess your car, motorbike, van, or commercial vehicle to decide on roadside repair or relocation for repair or storage. We can move your vehicle to any of our repair and storage facilities in the South East or a destination of your choice. Our emergency callout lines are available 24/7, ensuring we're there when you need us.
                </span>
                <img alt="accident recovery" src="./assets/images/accident-recovery.png" />
            </div>
        </div>


        <div class="services__list-content">
            <hr id="vehicle-storage" />
            <h1>Vehicle Storage</h1>
            <div class="services__list-content__item">
                <span>
                    At FirstLine Recovery, we offer robust vehicle storage solutions. We are equipped to store a wide range of vehicles, including cars, motorbikes, caravans, motorhomes, buses, and commercial vehicles. Our facility is not just a storage space, it's a fortress for your vehicle. We have invested heavily in security, with 24/7 CCTV monitoring, on-site security personnel, rapid response alarms, high exterior walls, and restricted access to provide complete peace of mind.
                    <br />
                    <br />
                    When you decide to retrieve your vehicle, our efficient office team is at your service. They will verify your ownership, collect delivery details, and arrange a convenient delivery time. Our lines are open 24/7, ensuring you can reach us at any time. FirstLine Recovery's secure vehicle storage services are competitively priced with excellent rates for long-term storage, making us your reliable partner for secure and efficient vehicle storage solutions.
                </span>
                <img alt="vehicle storage" src="./assets/images/vehicle-storage.png" />
            </div>
        </div>


        <div class="services__list-content">
            <hr id="vehicle-transportation" />
            <h1>Vehicle Transportation</h1>
            <div class="services__list-content__item">
                <span>
                    FirstLine Recovery provides a dependable vehicle transportation service for various types of vehicles. Catering to businesses and private individuals, our team is available 24/7 and offers a flexible, transparent process. With a strong local presence, our drivers are familiar with the delivery area, guaranteeing timely and safe vehicle deliveries.
                    <br />
                    <br />
                    Prior to transportation, we conduct a thorough vehicle inspection and agree on the condition with you. Upon delivery, we review the appraisal with the recipient, ensuring your vehicle's safe arrival. For classic and high-value vehicles, our fleet includes transporters for low clearance cars, ensuring your vehicle arrives in perfect, show-ready condition.
                    <br />
                    <br />
                    We offer services for lease vehicle deliveries, private vehicle sales, and transportation of non-runners, supercars, and larger vehicles. Our office staff, chosen for their logistics expertise, gather all necessary information efficiently. They manage all details of the vehicle, pickup and delivery, and allocate the most suitable transporter. Throughout the process, they address any queries and keep you updated on the delivery progress.
                </span>
                <img alt="vehicle transportation" src="./assets/images/vehicle-transportation.png" />
            </div>
        </div>

        <div class="services__list-content">
            <hr id="police-collections" />
            <h1>Police & Compound Collections</h1>
            <div class="services__list-content__item">
                <span>
                    FirstLine Recovery is ready to assist when your vehicle needs to be retrieved following a serious accident or impounding by authorities. Our experienced team simplifies the recovery process by guiding you through the necessary steps and helping with paperwork where possible.
                    <br />
                    <br />
                    We validate your ownership and collaborate with authorities for a smooth release and return of your impounded vehicle. Our diverse fleet can handle all types of vehicles - from high-value cars to damaged non-runners and commercial vehicles. Our comprehensive insurance ensures your vehicle's protection until it's safely delivered to you.
                    <br />
                    <br />
                    With FirstLine Recovery’s police and compound collection services, you can expect a quick, discreet, and hassle-free experience. We're available 24/7 for your convenience.

                </span>
                <img alt="police & compound collections" src="./assets/images/police-collections.png" />
            </div>
        </div>

        <div class="services__list-content">
            <hr id="abandoned-removal" />
            <h1>Abandoned Vehicle Removal</h1>
            <div class="services__list-content__item">
                <span>
                    Each year, numerous vehicles are left abandoned in England, causing problems for businesses and individuals. FirstLine Recovery partners with local councils and enforcement agencies to swiftly remove these vehicles, handling all legal paperwork for a smooth process.
                    <br />
                    <br />
                    While there's no strict legal definition for an "abandoned vehicle", signs like long immobility, missing parts, and unroadworthy conditions can justify removal. We ensure all necessary legal steps are followed and liaise with police when needed.
                    <br />
                    <br />
                    In cases where removal is resisted, we continue to represent your interests until the vehicle is legally removed. Our fleet can handle vehicles of all sizes and conditions. If you're unsure whether a vehicle is abandoned, contact us. Our team will quickly assess the situation and offer guidance.
                </span>
                <img alt="abandoned vehicle removal" src="./assets/images/abandoned-removal.png" />
            </div>
        </div>
        <div class="services__list-content">

            <hr id="bailiff-recovery" />
            <h1>Bailiff Recovery</h1>
            <div class="services__list-content__item">
                <span>
                    FirstLine Recovery provides professional and sensitive vehicle repossession services for car-finance lenders grappling with persistent missed payments. Our team directly interacts with customers, striving to settle arrears and minimize distress. In case of payment failure, we conduct a comprehensive vehicle assessment, obtain an Appraisal Agreement, and carry out the repossession, even resorting to keyless total lift when necessary.
                    <br />
                    <br />
                    Capable of handling various vehicle types, our efficient staff is prepared to quickly gather the necessary information and initiate the bailiff recovery process. With FirstLine Recovery, you can trust that the repossession process will be handled professionally and with maximum consideration given to all parties involved.
                </span>
                <img alt="bailiff recovery" src="./assets/images/bailiff-recovery.png" />
            </div>
        </div>
        <div class="services__list-content">


            <hr id="keyless-recovery" />
            <h1>Keyless/Total Key Lift Recovery</h1>
            <div class="services__list-content__item">
                <span>FirstLine Recovery offers expert keyless, total lift recovery services around the clock in London. Our versatile recovery vehicles can handle nearly any vehicle up to five tonnes, even without keys. Whether your vehicle has been in an accident, broken down, or damaged, our professional team is ready to assist at any time.
                    <br />
                    <br />
                    Our experienced recovery experts are prepared to handle a variety of vehicles promptly and efficiently. We aim to alleviate the stress of vehicle breakdowns by providing quick and efficient recovery. Depending on your location, we can reach you within 30 minutes of your call and transport your vehicle to the desired location, regardless of its condition. Even severely damaged or wheelless vehicles can be securely strapped to our trucks for transport.</span>
                <img alt="keyless/total key lift recovery"src="./assets/images/keyless-recovery.png" />
            </div>
        </div>

        <div class="services__list-content">
            <hr id="commercial-recovery" />
            <h1>Commercial Recovery</h1>
            <div class="services__list-content__item">
                <span>
                    Breakdowns and accidents involving your fleet can disrupt schedules and impact your business reputation. FirstLine Recovery understands the effects of commercial vehicle issues and responds quickly and efficiently. Our dedicated team, available 24/7, gathers necessary information promptly and dispatches the nearest recovery vehicle, all of which have GPS tracking for precise arrival estimates.
                    <br />
                    <br />
                    We aim to repair your commercial vehicle roadside when possible, but can also safely transport it to a specialist repair center if needed. Operating across various locations, our fleet can perform heavy winching, light recovery, and off-road assistance for buses, coaches, lorries, and trucks. Our professional operators are equipped with all necessary tools for diagnostics and recovery, ensuring prompt service. We offer both one-off callouts and regular contracts for our reliable commercial vehicle recovery service, with the latter option providing benefits like lower rates and quicker incident reporting.
                </span>
                <img alt="commercial recovery" src="./assets/images/commercial-recovery.png" />
            </div>
        </div>

        <div class="services__list-content">
            <hr id="fleet-services" />
            <h1>Fleet Vehicle Services</h1>
            <div class="services__list-content__item">
                <span>
                    Managing a fleet requires ensuring each vehicle's condition, warranty, and resale value. FirstLine Recovery in London provides comprehensive fleet services, including regular servicing, maintenance, and repairs. We collect vehicles, keep you updated on service progress, and handle all aspects of maintenance, MOT checks, or repairs. If unplanned repairs are needed, we notify you immediately and may offer a courtesy car.
                    <br />
                    <br />
                    Vehicles are returned to your premises upon service completion, and no additional work is carried out without your authorization. We offer competitive, negotiable rates for our thorough services, performed with attention to detail and following manufacturer guidelines. All work is guaranteed and parts used for repairs match the original vehicle parts, preserving your warranty. Contact us for a competitive, no-obligation quote on regular servicing and maintenance contracts.
                </span>
                <img alt="fleet vehicle services" src="./assets/images/fleet-services.png" />
            </div>
        </div>

        <div class="services__list-content">
            <hr id="scrap-vehicle" />
            <h1>Scrap Vehicle Collections</h1>
            <div class="services__list-content__item">
                <span>
                    Deciding to scrap a vehicle can avoid unnecessary expenses and stress. FirstLine Recovery offers a fully transparent and documented scrap vehicle collection service in London and surrounding areas. Our fleet can transport most vehicles, including non-runners and larger vehicles like motorhomes and buses. It's crucial to ensure proper disposal of end-of-life vehicles to adhere to legislation and avoid future liabilities.
                    <br />
                    <br />
                    Cars sent for scrapping must go to an Authorised Treatment Facility to ensure safe disposal and recycling. You'll receive a Certificate of Destruction once the vehicle is destroyed. Our knowledgeable team guides you through the process, helping with required documentation. We offer quick collections, open 24/7, making us the ideal choice when your vehicle fails MOT, is uninsured for driving, is non-running, or if you lack the time to arrange scrapping.
                </span>
                <img alt="scrap vehicle collections" src="./assets/images/scrap-vehicle.png" />
            </div>
        </div>
    </div>

    </div>


</section>