<section class="terms-and-conditions">
    <div class="terms-and-conditions__header">
        <h1>FirstLine Recovery Terms and Conditions of Use</h1>
    </div>

    <div class="terms-and-conditions__content">

        <b>Last Updated:</b> August 2023
        <p>
            <b>Introduction</b>
            <br />
            FirstLine Recovery Ltd ("FirstLine") provides this website and related services to you, subject to the following terms and conditions. By using this website or any of our services, you agree to these terms. Please review them carefully.
        </p>
        <p>

            <b>Provision of Services</b>
            <br />
            FirstLine provides vehicle breakdown recovery, transportation, storage, and associated services. We make reasonable efforts to ensure these services are available but cannot guarantee constant availability.
        </p>
        <p>

            <b>Access and Use</b>
            <br />
            We grant you temporary access to this website. We reserve the right to suspend, withdraw, or amend the website or services without notice. We are not liable if the website is unavailable. We may restrict access to parts or all of the website.
        </p>
        <p>

            <b>External Sites</b>
            <br />
            This website may contain links to third party sites. FirstLine is not responsible for those sites or any loss/damage arising from their use. Their terms of use apply.
        </p>
        <p>

            <b>Intellectual Property</b>
            <br />
            All content on this website remains the property of FirstLine or its licensors, protected by copyright law. You may only use it for personal, non-commercial purposes.
        </p>
        <p>

            <b>Prohibited Conduct</b>
            <br />
            You may not misuse this website, commit any criminal offense, distribute viruses/malicious code, infringe rights, send spam, or affect website functionality. We report violations to authorities.
        </p>
        <p>

            <b>Privacy</b>
            <br />
            Please see our Privacy Policy regarding how we collect, use, and protect your personal information.
        </p>
        <p>

            <b>Disclaimers</b>
            <br />
            We provide this website and services “as is” without warranty. You use them at your own risk. We are not liable for any damages arising from use.
        </p>
        <p>

            <b>Indemnity</b>
            <br />
            You agree to fully indemnify FirstLine against any damages or costs arising from your breach of these terms.
        </p>
        <p>

            <b>Changes</b>
            <br />
            We may modify these terms at any time. Continued use signifies acceptance of the changes.
        </p>
        <p>

            <b>Severability</b>
            <br />
            If any provision hereof is deemed unenforceable, the remaining provisions will continue in effect.
        </p>
        <p>

            <b>Governing Law</b>
            <br />
            These terms are governed by English law. Any disputes will be resolved exclusively in English courts.
        </p>
        <b>Contact Us</b>
        <p>
            Please contact us at <a href="mailto:info@firstline-recovery.com">info@firstline-recovery.com</a>with any questions about these terms.
        </p>
    </div>
</section>